### ISSUE TITLE
Return execution return value in the Create and Create2 methods in the Concrete environment

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#32]
# Rationale

Right now, `concrete.Environment.Create` and `concrete.Environment.Create2` ignore the return value of the bytecode execution. This is undesirable as it contains the revert reason when the contract creation reverts.

# Implementation

Modify the Concrete environment interface and implementation so the `Create` and `Create2` return the return value of the bytecode execution.

```go
// Current interface
type Environment interface {
	// ...
	Create(data []byte, value *uint256.Int) (common.Address, error)
	Create2(data []byte, endowment *uint256.Int, salt *uint256.Int) (common.Address, error)
}

// Desired interface
type Environment interface {
	// ...
	Create(data []byte, value *uint256.Int) ([]byte, common.Address, error)
	Create2(data []byte, endowment *uint256.Int, salt *uint256.Int) ([]byte, common.Address, error)
}
```

> **[ODHack 4.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

**Comment by vibenedict** [comment]
I would like to work on this fix

**Comment by fabrobles92** [comment]
Hello, Fabricio Robles here.

I would like to work on this issue :D

I have contributed to others web 3 open source projects such as Dojo Engine and would love to be part on the effort of this one.

**Comment by Adecom16** [comment]
@therealbytes i am Adeoluwa, A smart contract developer can i work on this

**Comment by TropicalDog17** [comment]
Hi @therealbytes, may I take this issue?

I have experience in programming with Go, and also contributed to various open source blockchain projects. 

To tackle this issue, my initial approach will be modify the interface and the implementation of Create and Create2. After that, I will fix any arise compiler error due to breaking change of the interface. And of course I will make sure existing tests still pass after the changes

**Comment by ghost** [comment]
@therealbytes can I be assigned this issue please? This is my first time in Starknet ecosystem and I’d love to be given the opportunity to proof my acquired skill. Thank you 🙏🏾

**Comment by therealbytes** [comment]
Hey! @more-of-odeh This is not a Starknet project. How familiar are you with Go and Ethereum?

**Comment by more-of-odeh** [comment]
Hello @therealbytes ,To solve this issue, I will change the signatures of Create and Create2 methods to return a byte slice along with the address and error. Next, I will update the implementations of these methods to capture the bytecode execution's return value. I will ensure the return value is correctly propagated back to the caller. I may also need to update any code that calls these methods to handle the new return values appropriately. Kindly assign me so I can start please, Thank you.🙏🏾
