### ISSUE TITLE
[ODHack 5.0] Remove Concrete dependency from core/state

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#33]
> **[ODHack 5.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

# Rationale

Concrete is not actually used by core/state but it is imported by `statedb.go` for interface checking `var _ cc_api.StateDB = (*StateDB)(nil)` and argument typing `concretePrecompiles concrete.PrecompileMap`. This is unfortunate since it makes it impossible to import `state` from `concrete` and `concrete/api` where it would be useful for testing since that would lead to an import cycle error.

# Implementation

- The interface check should be moved somewhere else. Probably `concrete/api/interface_go.go`.
- concretePrecompiles concrete.PrecompileMap should be replaced by an alternative type such as `[]common.Address` or `map[common.Address]interface{}` and all of the calls to the modified functions be updated accordingly.

**Comment by kateberryd** [comment]
@therealbytes I would love to work on this

**Comment by Jemiiah** [comment]
@therealbytes i would love to work on this

**Comment by therealbytes** [comment]
Any news on this? @Jemiiah

**Comment by Jemiiah** [comment]
hello @therealbytes I’m still working on this at least before Wednesday ends I would create my PR🙌🏾
thank you

**Comment by therealbytes** [comment]
What's your status on this? @Jemiiah

**Comment by Jemiiah** [comment]
Hello @therealbytes i will give you feedback later today🙌🏾

**Comment by Josh-121** [comment]
Hello. I'm looking to make my first contribution and. I'll review the codebase while taking note of the highlighted importation, I've had some experience working on something similar and looking to complete within 2days if assigned

**Comment by Bosun-Josh121** [comment]
Hello. I'm looking to make my first contribution here. I'll review the codebase while taking note of the highlighted implementation, I've had some experience working on something similar and looking to complete within 2days if assigned

**Comment by therealbytes** [comment]
@Josh-121 Any updates?

**Comment by Shoetan** [comment]
Hi @therealbytes can I be assigned this issue to solve import cycle problem which can be explained simply like 


A imports B
B imports A

**Comment by Bosun-Josh121** [comment]
> @Josh-121 Any updates?
 Will make pr soon

**Comment by Bosun-Josh121** [comment]
@therealbytes You can unassign by tomorrow if not ready. Sorry for the delay

**Comment by therealbytes** [comment]
Hey @Josh-121 This is blocking @Shoetan and it has been a week already.

ODHack ends this Sunday. If you are going to do deliver please do it soon enough that @Shoetan has time to finish his work on time. If you don't plan on delivering, it's ok but please let us know now so someone else can do it.

**Comment by Bosun-Josh121** [comment]
On my system now. Should see in some minutes

**Comment by Bosun-Josh121** [comment]
PR is ready

**Comment by rajeshkumarrobert** [comment]
Hi @therealbytes I love to work on this issue
