### ISSUE TITLE
Test state methods in Concrete environment

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#34]
> **[ODHack 5.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

# Rationale

Currently, the Concrete environment is poorly tested.

# Implementation

This depends on #33 being implemented. Once that is done, the mock statedb in `concrete/mock` can be moved to/reimplemented within `concrete/api` to have an in-memory statedb for testing. Both execution and gas usage should be tested.

At the moment, the state methods are:

```go
type Environment interface {
	// ...

	StorageLoad(key common.Hash) common.Hash
	StorageStore(key common.Hash, value common.Hash)
	Log(topics []common.Hash, data []byte)

	GetBalance(address common.Address) *uint256.Int
	GetCode(address common.Address) []byte
	GetCodeSize() int
	GetExternalBalance(address common.Address) *uint256.Int
	GetExternalCode(address common.Address) []byte
	GetExternalCodeSize(address common.Address) int
	GetExternalCodeHash(address common.Address) common.Hash
}
```

Note two more methods will be added by #31 .

**Comment by Naomi-Gift** [comment]
@therealbytes Can i work on this?

**Comment by Adecom16** [comment]
I am Adeoluwa, A smart contract developer @therealbytes assign this to me

**Comment by therealbytes** [comment]
@Adecom16 Any updates?

**Comment by therealbytes** [comment]
Assigned to @Gift-Naomi since @Adecom16 has not provided any updates in almost a week.

**Comment by Shoetan** [comment]
@therealbytes I would love to get on with this by creating all necessary test files ending with _test.go

Import go built in testing module

Write test functions taking pointer to the testing package (t *testing. T)

**Comment by therealbytes** [comment]
@Shoetan Any progress here?

**Comment by Shoetan** [comment]
@therealbytes I saw from the comments that this depends on issue 33 and the last time I checked it issue 33 is not closed yet.

**Comment by therealbytes** [comment]
@Shoetan Would you like to work on 33 instead?

**Comment by Shoetan** [comment]
@therealbytes ok I can try.

**Comment by Iwueseiter** [comment]
@therealbytes can I work on this issue if @Shoetan is taking #33?

**Comment by CristopherAguilar10** [comment]
Hello @therealbytes, i’m interested in working on my first issue, and this one seems quite interesting to me. Since there have been no updates recently, I would like to propose a possible solution that I have in mind.

**Comment by Shoetan** [comment]
@therealbytes I see issue: https://github.com/concrete-eth/concrete-geth/issues/33 is closed now. Is this issue still open?

**Comment by therealbytes** [comment]
@Shoetan Someone is already working on it but #68 is up for grabs.

**Comment by fishonamos** [comment]
Hi @therealbytes . As discussed.  Kindly assign.
