### ISSUE TITLE
Test block context methods in Concrete environment

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#40]
# Rationale

Currently, the Concrete environment is poorly tested.

# Implementation

This depends on #37 being implemented. Once that is done, the new mock block context can be used for testing. Both execution and gas usage should be tested.

At the moment, the block context methods are:

```go
type Environment interface {
	// ...

	GetBlockNumber() uint64
	GetBlockGasLimit() uint64
	GetBlockTimestamp() uint64
	GetBlockDifficulty() *uint256.Int
	GetBlockBaseFee() *uint256.Int
	GetBlockCoinbase() common.Address
	GetPrevRandom() common.Hash
	GetBlockHash(block uint64) common.Hash
}
```

> **[ODHack 4.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

**Comment by EjembiEmmanuel** [comment]
@therealbytes I'd love to work on this

**Comment by Osatuyi** [comment]
Hi @therealbytes can I please be assigned this issue.

**Comment by aji70** [comment]
hi @therealbytes i would love to work on this

**Comment by Iwueseiter** [comment]
@therealbytes can I work on this issue when #37 has been completed, I will conduct the tests, I would use Go test tool to: ensure all methods function as expected. I would make sure it return the expected outputs for the specified inputs. Call the methods on the mock implementations and use assertions to verify that actual outputs match expected outputs.

**Comment by therealbytes** [comment]
Any progress? @Iwueseiter

**Comment by Iwueseiter** [comment]
@therealbytes yes, I will create a PR as soon as possible.

**Comment by od-hunter** [comment]
Can I be assigned this project please?

**Comment by Iwueseiter** [comment]
@therealbytes I have opened a PR already.

**Comment by therealbytes** [comment]
Since @Iwueseiter is not responding maybe @aji70 can finish #55 instead?

**Comment by aji70** [comment]
Okay let me get to work

**Comment by Iwueseiter** [comment]
@therealbytes please i will update the PR today. I wasn't online cos of some challenges. I'm just seeing this.

**Comment by therealbytes** [comment]
@aji70 Please wait a couple days before working on this!
