### ISSUE TITLE
[ODHack 5.0] Pass test object to testtool

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#57]
> **[ODHack 5.0] Contributors**: Note that we highly recommend that you comment on the issue by introducing yourself and how you plan on tackling the issue! Just saying you want an issue is not helpful.  This will help with assigning tasks, especially if many comment.

# Rationale

Testtool is exclusively used for testing yet it is not integrated with golang's built-in testing tooling.

# Implementation

Modify `RunTestContract`, and `Test` in `testtool.go` to take a `t *testing.T` argument and:
- Instead of printing with `fmt`, use `t.Log`
- Have every tests be a subtest using `t.Run` that fails with `t.Fail` on failure instead of returning success and failure count

**Comment by adrianvrj** [comment]
Hello can I hop on this?

My name is Adrian Vargas, I am a beginner in this web3 world looking forward to collaborate as much as I can to learn everything I might need to become an experienced developer.

This is how I would approach this issue:
- Update the function signatures
- Update logging and subtests:
	1.	Use t.Log for Logging:
	•	Replace all fmt print statements with t.Log.
	2.	Use t.Run for Subtests:
	•	Wrap each individual test within a t.Run call.
	•	Use t.Fail to indicate a failure within a subtest.
- Run tests and make sure everything is fine including formatting
