### ISSUE TITLE
Wrong ordering for encoded input to call ops in concrete environment

### ISSUE THREAD

**Issue by therealbytes** [concrete-eth/concrete-geth#59]
As reported by @fabrobles92, the ordering of arguments when encoding the input for calls, static calls, and delegate calls in the concrete environment is wrong.
Right now it is (gas, address, [value], data) when it should be (address, data, gas, [value]).

**Comment by EmmanuelAR** [comment]
Heyyyy can I solve it ? @therealbytes i will check the current implementation and validate if in it wrong let me know 

Steps:

1. **Locate the Code**: Find the functions where arguments are encoded for calls, static calls, and delegate calls.
   
2. **Identify the Current Order**: Confirm that the current order is `(gas, address, [value], data)`.

3. **Modify the Order**: Change the order to `(address, data, gas, [value])`.

4. **Test the Changes**: Run tests to ensure the modifications work correctly.

5. **Review and Refactor**: Ensure the changes are clean and consistent throughout the codebase.

**Comment by Bosun-Josh121** [comment]
I've gone in to review the code and could fix this rather quickly. I have a software engineering background and looking to make my first contribution on here. Link to my od hack: 
https://app.onlydust.com/u/Josh-121
please assign if available
